# Лаба 1, Задание 1 📝

### 1. Синтетический тест: Концентрация меры на сфере $\mathbb{S}^{d-1}$

In [1]:
import numpy

In [4]:
# Количество векторов.
M = 20000

# Размерности пространств.
Ds = [16, 64, 256, 512, 4096]

In [10]:
d = Ds[0]

X = numpy.array([
    numpy.random.normal(0.0, 1.0, (d)) for _ in range(M)
])

Y = numpy.array([
    numpy.random.normal(0.0, 1.0, (d)) for _ in range(M)
])

X[0], numpy.linalg.norm(X[0]), Y[-1], numpy.linalg.norm(Y[-1])

(array([ 0.69794695,  0.17523994, -0.51136086, -0.75343704, -1.40601424,
         0.91902029,  0.15128041,  0.36096119,  0.01683542, -1.59746264,
         0.03262149,  0.97261459, -1.19748652, -0.13713869, -0.10830547,
         1.00674347]),
 np.float64(3.2091909312408626),
 array([-0.13495257,  1.43265155,  0.21585081, -0.83468382, -1.10242224,
         0.26581489,  0.48941971,  1.13693624,  1.65481822, -1.27545914,
        -1.10373579,  0.44665314, -0.05049533,  1.65685779, -0.33262171,
        -0.76323268]),
 np.float64(3.854345502596404))

In [11]:
for i in range(M):
    X[i] /= numpy.linalg.norm(X[i])
    Y[i] /= numpy.linalg.norm(Y[i])
    
X[0], numpy.linalg.norm(X[0]), Y[-1], numpy.linalg.norm(Y[-1])

(array([ 0.21748377,  0.05460564, -0.15934261, -0.23477476, -0.43812109,
         0.28637134,  0.04713973,  0.11247732,  0.005246  , -0.49777737,
         0.01016502,  0.30307159, -0.37314281, -0.04273311, -0.03374853,
         0.31370632]),
 np.float64(1.0),
 array([-0.0350131 ,  0.37169775,  0.05600194, -0.21655657, -0.28602061,
         0.06896499,  0.12697868,  0.29497518,  0.42933832, -0.33091458,
        -0.2863614 ,  0.115883  , -0.01310088,  0.42986748, -0.08629784,
        -0.19801875]),
 np.float64(1.0))

In [14]:
S = numpy.zeros(M)

for i in range(M):
    S[i] = numpy.dot(X[i], Y[i])

S[0], S[1]

(np.float64(-0.4987014797531248), np.float64(-0.13469718663811478))